- hosts: all #all or qa or localhost
  become: yes
  vars: 
    packages: 
      - apache2
      - tree
      - unzip
    hello: world
  tasks: 
  - name: Install packages
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    when: hello == "world"

  - name: Start service apache, if not started #systemctl
    ansible.builtin.service:
      name: apache2
      state: started #stopped or restarted or reloaded. always active work
      enabled: yes #enable

  # - name: Execute the command in remote shell #shell modules should be used if no options
  #   ansible.builtin.shell: useradd tim
   
  - name: add users #loop, because we cannot use list for this command
    ansible.builtin.user:
      name: "{{ item }}"
    loop:
      - tim
      - ann
      - brad
